In [44]:
import numpy as np

def generate_initial_solution(n_groups: int, n_per_group: int, n_rounds: int):
    n_golfers = n_groups * n_per_group
    schedule = np.zeros((n_rounds, n_groups, n_per_group), dtype=int)

    for r in range(n_rounds):
        # Random permutation of all golfers
        perm = np.random.permutation(n_golfers)
        # Split into groups
        schedule[r] = perm.reshape(n_groups, n_per_group)

    return schedule

def solve_golfer(n_groups: int, n_per_group: int, n_rounds: int) :
    '''
    Tries to solves the given golfer instance using simulated annealing.
    '''

    initial_solution = generate_initial_solution(n_groups, n_per_group, n_rounds)
    print(initial_solution)

In [58]:
g = generate_initial_solution(2, 4, 2)
g.shape
print(g)
n_rounds, n_groups, n_per_group = g.shape
rmd_round = np.random.randint(0, n_rounds)

rmd_group_1 = np.random.randint(0, n_groups)
rmd_group_2 = np.random.randint(0, n_groups)
while rmd_group_1 == rmd_group_2:
    # make sure that rmd_group_1 and rmd_group_2 are different
    rmd_group_2 = np.random.randint(0, n_groups)

rmd_group_pos_1 = np.random.randint(0, n_per_group)
rmd_group_pos_2 = np.random.randint(0, n_per_group)

tmp = g[rmd_round][rmd_group_1][rmd_group_pos_1]

print(f"{rmd_round}, {rmd_group_1}, {rmd_group_2}, {rmd_group_pos_1}, {rmd_group_pos_2}")
print(f"swapping: {g[rmd_round][rmd_group_1][rmd_group_pos_1]} and {g[rmd_round][rmd_group_2][rmd_group_pos_2]}")
g[rmd_round][rmd_group_1][rmd_group_pos_1] = g[rmd_round][rmd_group_2][rmd_group_pos_2]
g[rmd_round][rmd_group_2][rmd_group_pos_2] = tmp

g


[[[3 7 4 2]
  [0 6 5 1]]

 [[5 6 1 4]
  [2 3 7 0]]]
1, 1, 0, 1, 2
swapping: 3 and 1


array([[[3, 7, 4, 2],
        [0, 6, 5, 1]],

       [[5, 6, 3, 4],
        [2, 1, 7, 0]]])

In [86]:
n_rows, n_groups, n_per_group = g.shape 
golfers = n_groups * n_per_group
print(g)

from itertools import combinations

cost = 0
pair_counts = {}


for r in range(n_rounds):
    for group in g[r]:
        for g1, g2 in combinations(group, 2):
            pair = tuple(sorted((g1, g2)))
            pair_counts[pair] = pair_counts.get(pair, 0) + 1

# penalize repeated pairings
for pair, cnt in pair_counts.items():
    if cnt > 1:
        cost += (cnt - 1)  # first pairing is allowed, extras are bad


print(pair_counts)
cost


[[[3 7 4 2]
  [0 6 5 1]]

 [[5 6 3 4]
  [2 1 7 0]]]
{(np.int64(3), np.int64(7)): 1, (np.int64(3), np.int64(4)): 2, (np.int64(2), np.int64(3)): 1, (np.int64(4), np.int64(7)): 1, (np.int64(2), np.int64(7)): 2, (np.int64(2), np.int64(4)): 1, (np.int64(0), np.int64(6)): 1, (np.int64(0), np.int64(5)): 1, (np.int64(0), np.int64(1)): 2, (np.int64(5), np.int64(6)): 2, (np.int64(1), np.int64(6)): 1, (np.int64(1), np.int64(5)): 1, (np.int64(3), np.int64(5)): 1, (np.int64(4), np.int64(5)): 1, (np.int64(3), np.int64(6)): 1, (np.int64(4), np.int64(6)): 1, (np.int64(1), np.int64(2)): 1, (np.int64(0), np.int64(2)): 1, (np.int64(1), np.int64(7)): 1, (np.int64(0), np.int64(7)): 1}


4